### ISSUE TITLE
Arrays in query params

### ISSUE THREAD

**Issue by demershov** [Djaler/vue-use-route-query#46]
Hi Kirill,
Thank's for developing for the open source.

I have a question, what to do with the array of values for the URL query param? For example - `url?query=alpha,beta,gamma`
Because adding a new value to the computed variable, that is array, isn't calling the `set()` in computed.

Cheers.

**Comment by Djaler** [comment]
Hello. Can you provide a reproduction for your problem?

**Comment by demershov** [comment]
Yep, of course.
Suppose we have a filter, the value of which can be several values at the same time, usually in the URL I saw it as `https://url?some-query=value1,value2,value3`

I've attempted the following, but it doesn't work.
```js
const filters = reactive({
        someFilterName: useRouteQuery("some-query", [], {
            fromQuery(value) {
                return value.split(",");
            },

            toQuery(value) {
                return value.join(",");
            },
        }),
});

function addValueToSomeFilterName(value = " ") {
        filters.someFilterName.push(value)
}
```
Of course, I can do the following:
```js
function addValueToSomeFilterName(value = " ") {
        filters.someFilterName.push(value);
        filters.someFilterName = filters.someFilterName;

}
```
But it seems strange to me, at least.

What do you think about it?
Best wishes.

**Comment by Djaler** [comment]
I have an idea how to handle this. Will try to do someting

**Comment by demershov** [comment]
> I have an idea how to handle this. Will try to do someting

Thanks for your answer. 
I'm interested in the direction of your proposed solution. Are you going to refuse from `computed` property?

**Comment by Djaler** [comment]
No, I think I can wrap a value created in `get` into `reactive` and watch it for changes

**Comment by Djaler** [comment]
Maybe you can take a look at #47

**Comment by demershov** [comment]
I looked at your solution, thank you.

It seems to be working. It's a little confusing me to create a watcher every time, but it's working. It seems that need to assign the result of stopping the watcher to a variable, isn't it?

**Comment by Djaler** [comment]
There are no result of stopping the watcher

**Comment by demershov** [comment]
> There are no result of stopping the watcher

A little suffocating.
Yep, it's returns undefined, but the variable keeps storing the function after stopped, isn't it? So checking with the optional chaining isn't quite correct.

**Comment by Djaler** [comment]
I think nothing bad will happen if I call stop more then once

**Comment by demershov** [comment]
You’re right. Thanks.
