### ISSUE TITLE
Late calling `onTrigger` in computed property

### ISSUE THREAD

**Issue by demershov** [Djaler/vue-use-route-query#48]
Hi @Djaler 

Suppose we have an `input ` connected via `v-model` to the search variable.
We don't want the changes to be written to the router immediately, so we make the variable `searchFilters = reactive({search: useRouteQuery()})`. When we submit the form, we assign the value from the `search` to the `searchFilter.search` `=>` `searchFilter.search = search.value` in the submit function and make a request. But due to microtasks, the old value that was stored in `searchFilter.search` before changes will be sent, because `OnTrigger` in the computed property will be executed later.

```vue
<template>
    <input v-model="search" type="text" />
    <button @click="onSubmit">Click</button>
</template>

<script setup>
    import { reactive, ref } from "vue";
    import { useRouteQuery } from "vue-use-route-query";

    const search = ref("oldString");
    const searchFilters = reactive({
        foo: "",
        search: useRouteQuery("search", ""),
    });

    function onSubmit() {
        searchFilters.search = search.value;

        new Promise((res) =>
            setTimeout(res, 0, [search.value, searchFilters.search])
        ).then((result) => console.log(...result));
    }
</script>
```

What do you think about it? Thank you.

**Comment by Djaler** [comment]
I have an idea how to handle this. What do you think about such API:
```
searchFilters.search = search.value;

await waitForQueryUpdate();

new Promise((res) =>
    setTimeout(res, 0, [search.value, searchFilters.search])
).then((result) => console.log(...result));
```

**Comment by demershov** [comment]
@Djaler,
The proposed option looks more concise than what came to my mind when I thought about this problem. But my solution is less concise and predictable, because it is built on macrotasks. I did it because it didn't require making changes to your solution.
```js
function onSubmit() {
        searchFilters.search = search.value;

        setTimeout(
            () =>
                new Promise((res) =>
                    setTimeout(res, 0, [search.value, searchFilters.search])
                ).then((result) => console.log(...result)),
            0
        );
}
```

But I don't quite understand how you want to write this, because as far as I remember, `set` in `computed` doesn't return a promise. So I'm wondering how you want to write the `await waitForQueryUpdate();` piece of code in more details.

Cheers.

**Comment by Djaler** [comment]
https://github.com/Djaler/vue-use-route-query/blob/master/packages/core/src/queue-query-update.ts#L7 here I have a query of all changes needs to be applied to route query.

So I can just do something like
```
export async function waitForQueryUpdate() {
    if (queryReplaceQueue) {
        await queryReplaceQueue.waitForFinish();
    }
}
```

Where `waitForFinish` in `AsyncQueue` is just
```
async waitForFinish() {
    if (queuePromise) {
        await queuePromise;
    }
}
```
https://github.com/Djaler/async-queue-chain/blob/master/src/index.ts#L12

**Comment by demershov** [comment]
Oh, yep, it makes a sense. Is it possible that a situation where `queuePromise` indicates not to the right `Promise` that we need, but the last one? Do you think this could lead to improper behavior?

**Comment by demershov** [comment]
Some thoughts:
The main nuance is that at the moment the **main truth** is the `URL`, changes in which occur asynchronously, at the same time, perhaps it would be better if the **main truth** were a variable. Maybe I'm wrong.

**Comment by Djaler** [comment]
> if the **main truth** were a variable

we can do it by creating a real variable for a value (return it in getter, update in setter) and two separate watchers to update query/watch for query changes

**Comment by demershov** [comment]
Yes, the first thing that came to my mind it's `ref`, before I saw your solution and the solution from vueuse. Anyway, perhaps our dialogue will make your package better. Thanks.

**Comment by dm1tr** [comment]
I think, we could close this issue, isn't it?
