### ISSUE TITLE
Navigation mode

### ISSUE THREAD

**Issue by jfern01** [Djaler/vue-use-route-query#59]
Hey, awesome library! I was wondering how difficult it would be to add the ability to change the navigation mode to push() instead of replace().

**Comment by Djaler** [comment]
I think it should be not so hard to pass a mode as an additional option. Buy what is your use case?

**Comment by jfern01** [comment]
I'm persisting some product filters to the route query and I need the user to be able to click back on their browser to navigate to the previous state.

**Comment by Djaler** [comment]
What do you think about such API?
```
useRouteQuery('foo', null, {
    navigationMode: 'push',
})

useRouteQuery('bar', null, {
    transformer,
    navigationMode: 'push',
})
```

**Comment by jfern01** [comment]
Personally, I would shorten it to just 'mode', but it's your library. I'm just happy to get the new feature!

**Comment by jfern01** [comment]
You could also do something like:

`useRouteQuery('bar', null, transformer, { mode: 'push' })`

The new parameter would be optional to not break your current API.

**Comment by Djaler** [comment]
Check out [version 1.3.0](https://github.com/Djaler/vue-use-route-query/releases/tag/v1.3.0)

**Comment by jfern01** [comment]
Works great! Thank you for your time.
