### ISSUE TITLE
Handling arrays with multiple param name occurrence

### ISSUE THREAD

**Issue by hawkend** [Djaler/vue-use-route-query#61]
Hi,

Would it be feasible to implement array query params like e.g.:
```javascript
const choice = useRouteQuery('choice', [], arrayTransformer)
// ?choice=a&choice=b
choice.value = ['a', 'b']
``` 

I have seen related issue with comma separated variant here:
https://github.com/Djaler/vue-use-route-query/issues/46

And there is a WIP branch of the feature in the issue before issue with comma separated values was not handled:
https://github.com/Djaler/vue-use-route-query/tree/arrays

**Comment by Djaler** [comment]
To be honest, I don't remember what was the problem with this branch and why I abandoned it.

But you can use arrays now, just with slightly different format in query:
```ts
const arrayTransformer: RouteQueryTransformer<string[]> = {
    toQuery(value: string[] | undefined): string | undefined {
        if (!value) {
            return undefined;
        }
        return value.join(',');
    },
    fromQuery(value: string): string[] | undefined {
        if (!value) {
            return undefined;
        }
        return value.split(',');
    },
};

const foo = useRouteQuery('foo', [], arrayTransformer);
// ?foo=a,b,c
foo.value = ['a', 'b', 'c']
```

**Comment by hawkend** [comment]
The problem I have had comes from the backend side where filtering for Many to Many relationships requires repeated param name. Library in presence of array takes the first values always. I took an approach where I treat route.query as main source of truth. Nevertheless I were able to solve this issue with custom params serializer and using comma separated values.

Unless we could specify via option custom getQueryValue if it makes a sense. 

I find the issue solved if getQueryValue should remain as private function.

**Comment by Djaler** [comment]
> I treat route.query as main source of truth

Do you send route query to backend? I don't think it should be used such way. If you want specific query in http request to backend - you can serialize data as you want. Route query is not intended for this.

**Comment by hawkend** [comment]
Yes, I have used to do it but I have refactored to do it differently. Leaky abstractions can sometimes lead to madness. Thanks for discussion, from my side I find the issue(or rather lack of it) solved. Cheers :-)
