### ISSUE TITLE
Question: why'd you choose to use a queue?

### ISSUE THREAD

**Issue by kylegl** [Djaler/vue-use-route-query#62]
Not an issue, im just curious why you chose to use a queue to update the route query? I was trying to implement something similar and stumbled on this.

Thanks!

**Comment by Djaler** [comment]
I have tried https://vueuse.org/router/useRouteQuery/#useroutequery, but it had a problem in case like this, because route.replace is async operation:
```
const foo = useRouteQuery('foo')
const bar= useRouteQuery('bar')
foo.value = 'foo'
bar.value = 'bar'
```

And I solved this by queuing updated.

BTW, looks like this is fixed now in vue-use

**Comment by kylegl** [comment]
I figured you were the one who wrote the vueuse useRouteQuery. Thanks for the info!
